const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const app=express(),PORT=Number(process.env.PORT)||4173,DEFAULT_STORE=path.join(__dirname,'data','store.json'),STORE=process.env.ANANTA_STORE_PATH||DEFAULT_STORE;
const isProduction=process.env.NODE_ENV==='production';
if(isProduction&&!process.env.APP_SECRET){console.error('FATAL: APP_SECRET is required when NODE_ENV=production');process.exit(1)}
const SECRET=process.env.APP_SECRET||crypto.randomBytes(48).toString('hex');
if(STORE!==DEFAULT_STORE&&!fs.existsSync(STORE)){fs.mkdirSync(path.dirname(STORE),{recursive:true});fs.copyFileSync(DEFAULT_STORE,STORE)}
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=(), usb=()');res.setHeader('Cross-Origin-Resource-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; object-src 'none'; frame-src 'none'; base-uri 'none'; form-action 'self'");next()});
app.use(express.json({limit:'512kb',strict:true}));app.use((req,res,next)=>{const scrub=v=>{if(typeof v==='string')return v.replace(/[<>]/g,'').slice(0,5000);if(Array.isArray(v))return v.map(scrub);if(v&&typeof v==='object'){for(const k of Object.keys(v))v[k]=scrub(v[k])}return v};if(req.body)req.body=scrub(req.body);next()});app.use(express.static(path.join(__dirname,'public'),{dotfiles:'deny',etag:true,maxAge:0}));
const read=()=>JSON.parse(fs.readFileSync(STORE,'utf8'));
const write=d=>{const tmp=STORE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(d,null,2),{mode:0o600});fs.renameSync(tmp,STORE)};
const id=p=>p+'_'+Date.now().toString(36)+crypto.randomBytes(4).toString('hex');
const now=()=>new Date().toISOString();const n=v=>Number(v)||0;const clean=(v,max=300)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,max);const fy=()=>{const d=new Date(),y=d.getMonth()>=3?d.getFullYear():d.getFullYear()-1;return `${y}-${String(y+1).slice(-2)}`};
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(String(password),salt,64).toString('hex');return `scrypt$${salt}$${hash}`}
function checkPassword(password,stored){if(!stored)return false;if(!stored.startsWith('scrypt$'))return crypto.timingSafeEqual(Buffer.from(String(password)),Buffer.from(String(stored)));const [,salt,hex]=stored.split('$'),got=crypto.scryptSync(String(password),salt,64);const expected=Buffer.from(hex,'hex');return expected.length===got.length&&crypto.timingSafeEqual(got,expected)}
function ensure(s){s.suppliers??=[];s.purchases??=[];s.quotations??=[];s.payments??=[];s.stockMovements??=[];s.creditNotes??=[];s.expenses??=[];s.auditLogs??=[];const settingDefaults={companyName:'ANANTA INDUSTRIES',companyAddress:'GIDC Naroda, Ahmedabad, Gujarat',companyGSTIN:'',companyState:'Gujarat',companyStateCode:'24',companyPincode:'',companyPhone:'',companyEmail:'',authorizedSignatory:'',bankName:'',accountNo:'',ifsc:'',upiId:'',defaultTerms:'Subject to Ahmedabad jurisdiction. Goods once sold are governed by agreed commercial terms.',invoicePrefix:'AI',quotationPrefix:'QT'};s.settings={...settingDefaults,...(s.settings||{})};s.invoices??=[];s.products??=[];s.clients??=[];s.users??=[];for(const u of s.users){if(u.password&&!u.passwordHash){u.passwordHash=hashPassword(u.password);delete u.password}u.active=u.active!==false}return s}
(function migrate(){const s=ensure(read());for(const k of ['cms','productCategories','catalogue','enquiries','bulkEnquiries','contactEnquiries','gallery','certificates','seo'])delete s[k];write(s)})();
function nextNo(s,type){const pref=type==='invoice'?(s.settings.invoicePrefix||'AI'):(s.settings.quotationPrefix||'QT'),arr=type==='invoice'?s.invoices:s.quotations,seq=arr.filter(x=>(x.number||'').includes(fy())).length+1;return `${pref}/${fy()}/${String(seq).padStart(4,'0')}`}
function sign(p){const payload={...p,iat:Date.now(),exp:Date.now()+8*60*60*1000,nonce:crypto.randomBytes(12).toString('hex')},b=Buffer.from(JSON.stringify(payload)).toString('base64url');return b+'.'+crypto.createHmac('sha256',SECRET).update(b).digest('base64url')}
function verify(t){try{const [b,s]=String(t||'').split('.'),e=crypto.createHmac('sha256',SECRET).update(b).digest('base64url');if(!s||s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e)))return null;const p=JSON.parse(Buffer.from(b,'base64url'));if(!p.exp||Date.now()>p.exp)return null;return p}catch{return null}}
function audit(s,req,action,detail=''){s.auditLogs.unshift({id:id('log'),date:now(),userId:req.user?.id||'',user:req.user?.name||'System',role:req.user?.role||'',action,detail:clean(detail,500)});s.auditLogs=s.auditLogs.slice(0,2000)}
function auth(req,res,next){const u=verify((req.headers.authorization||'').replace(/^Bearer\s+/i,''));if(!u)return res.status(401).json({error:'Session expired or unauthorized'});const current=ensure(read()).users.find(x=>x.id===u.id&&x.active!==false);if(!current||current.role!==u.role)return res.status(401).json({error:'Account unavailable'});req.user=u;next()}
function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Admin access required'});next()}
function billerOrAdmin(req,res,next){if(!['admin','biller'].includes(req.user.role))return res.status(403).json({error:'Access denied'});next()}
function safeClient(c,role){return role==='biller'?{id:c.id,name:c.name}:c}
function normItems(s,items,allowRate=true){if(!items?.length)throw Error('Add at least one item');let subtotal=0,cost=0;const rows=items.map(r=>{const p=s.products.find(x=>x.id===r.productId),qty=n(r.qty);if(!p||qty<=0||qty>100000)throw Error('Invalid item');const rate=allowRate&&r.rate!==undefined?n(r.rate):n(p.sellingPrice??p.price),base=rate*qty,tax=base*n(p.gst)/100;subtotal+=base;cost+=n(p.purchasePrice)*qty;return{productId:p.id,name:p.name,sku:p.sku,hsn:p.hsn||'',qty,unit:p.unit,rate,gst:n(p.gst),base,tax,total:base+tax,purchasePrice:n(p.purchasePrice)}});return{rows,subtotal,cost}}
function taxCalc(subtotal,discount,taxableTax,isInter){const ratio=subtotal>0?Math.max(0,(subtotal-discount))/subtotal:0,totalTax=taxableTax*ratio;if(isInter)return{taxable:Math.max(0,subtotal-discount),cgst:0,sgst:0,igst:totalTax,tax:totalTax};return{taxable:Math.max(0,subtotal-discount),cgst:totalTax/2,sgst:totalTax/2,igst:0,tax:totalTax}}
function recordStock(s,p,qty,type,ref,by,note=''){p.stock=n(p.stock)+qty;s.stockMovements.push({id:id('sm'),date:now(),productId:p.id,productName:p.name,sku:p.sku,type,qty,balance:p.stock,reference:clean(ref,100),createdBy:clean(by,100),note:clean(note,250)})}
const attempts=new Map();function loginLimit(req,res,next){const key=req.socket.remoteAddress||'local',x=attempts.get(key)||{count:0,until:0};if(x.until>Date.now())return res.status(429).json({error:'Too many login attempts. Try again shortly.'});req.loginKey=key;next()}
app.post('/api/login',loginLimit,(req,res)=>{const username=clean(req.body?.username,80),password=String(req.body?.password||''),s=ensure(read()),u=s.users.find(x=>x.username===username&&x.active!==false);if(!u||!checkPassword(password,u.passwordHash)){const x=attempts.get(req.loginKey)||{count:0,until:0};x.count++;if(x.count>=5){x.until=Date.now()+60_000;x.count=0}attempts.set(req.loginKey,x);return res.status(401).json({error:'Invalid username or password'})}attempts.delete(req.loginKey);const safe={id:u.id,name:u.name,username:u.username,role:u.role};audit(s,{user:safe},'LOGIN','Successful sign in');write(s);res.json({token:sign(safe),user:safe})});
app.get('/healthz',(req,res)=>res.status(200).json({ok:true,service:'ananta-industries',version:'3.0.1'}));
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/dashboard',auth,admin,(req,res)=>{const s=ensure(read()),valid=s.invoices.filter(i=>i.status!=='Cancelled'),sales=valid.reduce((a,b)=>a+n(b.total),0),paid=s.payments.reduce((a,b)=>a+n(b.amount),0),profit=valid.reduce((a,b)=>a+n(b.profit),0),expenses=s.expenses.reduce((a,b)=>a+n(b.amount),0);res.json({products:s.products.length,stockUnits:s.products.reduce((a,b)=>a+n(b.stock),0),clients:s.clients.length,invoices:valid.length,totalSales:sales,outstanding:Math.max(0,sales-paid),profit,expenses,netProfit:profit-expenses,lowStock:s.products.filter(p=>n(p.stock)<=n(p.lowStock)).length,recent:valid.slice(-5).reverse()})});
app.get('/api/products',auth,(req,res)=>{const rows=ensure(read()).products.map(p=>req.user.role==='biller'?{id:p.id,sku:p.sku,name:p.name,category:p.category,unit:p.unit,sellingPrice:n(p.sellingPrice??p.price),price:n(p.sellingPrice??p.price),gst:n(p.gst),stock:n(p.stock),lowStock:n(p.lowStock),hsn:p.hsn}:p);res.json(rows)});
app.post('/api/products',auth,admin,(req,res)=>{const s=ensure(read()),p={id:id('p'),sku:req.body.sku,name:req.body.name,category:req.body.category||'',hsn:req.body.hsn||'',unit:req.body.unit||'pcs',purchasePrice:n(req.body.purchasePrice),sellingPrice:n(req.body.sellingPrice??req.body.price),price:n(req.body.sellingPrice??req.body.price),gst:n(req.body.gst)||18,stock:n(req.body.stock),lowStock:n(req.body.lowStock)||10};s.products.push(p);audit(s,req,'PRODUCT_CREATE',p.name);if(p.stock)recordStock(s,p,0,'Opening','Opening Stock',req.user.name,'Initial balance');write(s);res.json(p)});
app.put('/api/products/:id',auth,admin,(req,res)=>{const s=ensure(read()),p=s.products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Not found'});const old=n(p.stock);Object.assign(p,req.body);p.purchasePrice=n(req.body.purchasePrice??p.purchasePrice);p.sellingPrice=n(req.body.sellingPrice??req.body.price??p.sellingPrice);p.price=p.sellingPrice;p.gst=n(req.body.gst??p.gst);p.stock=n(req.body.stock??p.stock);p.lowStock=n(req.body.lowStock??p.lowStock);if(p.stock!==old)s.stockMovements.push({id:id('sm'),date:now(),productId:p.id,productName:p.name,sku:p.sku,type:'Adjustment',qty:p.stock-old,balance:p.stock,reference:'Product Edit',createdBy:req.user.name,note:'Manual stock adjustment'});write(s);res.json(p)});
app.delete('/api/products/:id',auth,admin,(req,res)=>{const s=ensure(read());s.products=s.products.filter(p=>p.id!==req.params.id);write(s);res.json({ok:true})});
app.get('/api/stock-movements',auth,admin,(req,res)=>res.json(ensure(read()).stockMovements.slice().reverse()));
app.get('/api/clients',auth,(req,res)=>res.json(ensure(read()).clients.map(c=>safeClient(c,req.user.role))));
app.post('/api/clients',auth,admin,(req,res)=>{try{const s=ensure(read()),gst=clean(req.body.gst,20).toUpperCase(),stateCode=clean(req.body.stateCode,2)||(gst.match(/^\d{2}/)?.[0]||'');const c={id:id('c'),name:clean(req.body.name,120),company:clean(req.body.company,120),phone:clean(req.body.phone,30),email:clean(req.body.email,120),gst,state:clean(req.body.state,80)||'Gujarat',stateCode,pincode:clean(req.body.pincode,10),address:clean(req.body.address,300),deliveryAddress:clean(req.body.deliveryAddress,300)};if(!c.name)throw Error('Client name is required');if(gst&&!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(gst))throw Error('Enter a valid 15-character GSTIN');s.clients.push(c);audit(s,req,'CLIENT_CREATE',c.name);write(s);res.json(c)}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/clients/:id',auth,admin,(req,res)=>{try{const s=ensure(read()),c=s.clients.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Not found'});const gst=clean(req.body.gst,20).toUpperCase();if(gst&&!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(gst))throw Error('Enter a valid 15-character GSTIN');Object.assign(c,{name:clean(req.body.name,120)||c.name,company:clean(req.body.company,120),phone:clean(req.body.phone,30),email:clean(req.body.email,120),gst,state:clean(req.body.state,80)||c.state||'Gujarat',stateCode:clean(req.body.stateCode,2)||(gst.match(/^\d{2}/)?.[0]||c.stateCode||''),pincode:clean(req.body.pincode,10),address:clean(req.body.address,300),deliveryAddress:clean(req.body.deliveryAddress,300)});write(s);res.json(c)}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/clients/:id',auth,admin,(req,res)=>{const s=ensure(read());s.clients=s.clients.filter(c=>c.id!==req.params.id);write(s);res.json({ok:true})});
app.get('/api/suppliers',auth,admin,(req,res)=>res.json(ensure(read()).suppliers));
app.post('/api/suppliers',auth,admin,(req,res)=>{const s=ensure(read()),x={id:id('sup'),...req.body};s.suppliers.push(x);audit(s,req,'SUPPLIER_CREATE',x.name||'Supplier');write(s);res.json(x)});
app.delete('/api/suppliers/:id',auth,admin,(req,res)=>{const s=ensure(read());s.suppliers=s.suppliers.filter(x=>x.id!==req.params.id);write(s);res.json({ok:true})});
app.get('/api/purchases',auth,admin,(req,res)=>res.json(ensure(read()).purchases.slice().reverse()));
app.post('/api/purchases',auth,admin,(req,res)=>{try{const s=ensure(read()),sup=s.suppliers.find(x=>x.id===req.body.supplierId);if(!sup)throw Error('Select a valid supplier');if(!req.body.items?.length)throw Error('Add purchase items');let total=0;const items=req.body.items.map(r=>{const p=s.products.find(x=>x.id===r.productId),qty=n(r.qty),rate=n(r.rate);if(!p||qty<=0)throw Error('Invalid purchase item');const amount=qty*rate;total+=amount;p.purchasePrice=rate;recordStock(s,p,qty,'IN',req.body.billNo||'Purchase',req.user.name,`Purchase from ${sup.name}`);return{productId:p.id,name:p.name,qty,unit:p.unit,rate,amount}});const x={id:id('pur'),number:`PUR/${fy()}/${String(s.purchases.length+1).padStart(4,'0')}`,date:now(),supplierId:sup.id,supplierName:sup.name,billNo:req.body.billNo||'',items,total,notes:req.body.notes||'',createdBy:req.user.name};s.purchases.push(x);audit(s,req,'PURCHASE_CREATE',x.number);write(s);res.json(x)}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/quotations',auth,admin,(req,res)=>res.json(ensure(read()).quotations.slice().reverse().map(q=>req.user.role==='biller'?{...q,clientSnapshot:undefined}:q)));
app.post('/api/quotations',auth,admin,(req,res)=>{try{const s=ensure(read()),c=s.clients.find(x=>x.id===req.body.clientId);if(!c)throw Error('Select a valid client');const z=normItems(s,req.body.items),discount=Math.max(0,n(req.body.discount)),rawTax=z.rows.reduce((a,r)=>a+r.tax,0),isInter=(c.state||'Gujarat').toLowerCase()!==(s.settings.companyState||'Gujarat').toLowerCase(),tx=taxCalc(z.subtotal,discount,rawTax,isInter),q={id:id('qt'),number:nextNo(s,'quotation'),date:now(),validUntil:req.body.validUntil||'',clientId:c.id,clientName:c.name,clientSnapshot:{...c},items:z.rows,subtotal:z.subtotal,discount,...tx,total:tx.taxable+tx.tax,notes:req.body.notes||'',status:'Open',createdBy:req.user.name};s.quotations.push(q);write(s);const out={...q};if(req.user.role==='biller')delete out.clientSnapshot;res.json(out)}catch(e){res.status(400).json({error:e.message})}});
function createInvoice(s,req,payload,sourceQuotation){const c=s.clients.find(x=>x.id===payload.clientId);if(!c)throw Error('Select a valid client');const cfg=s.settings||{};const gst=String(cfg.companyGSTIN||'').trim().toUpperCase();if(!gst||!cfg.companyAddress||!cfg.companyState||!cfg.companyStateCode)throw Error('Admin must configure Company GSTIN, registered address, state and state code in Settings before generating GST invoices');if(!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(gst))throw Error('Company GSTIN in Settings is invalid');const z=normItems(s,payload.items),discount=Math.max(0,n(payload.discount));for(const r of z.rows){const p=s.products.find(x=>x.id===r.productId);if(r.qty>n(p.stock))throw Error(`Insufficient stock for ${p.name}`)}const rawTax=z.rows.reduce((a,r)=>a+r.tax,0),isInter=(c.state||'Gujarat').toLowerCase()!==(cfg.companyState||'Gujarat').toLowerCase(),tx=taxCalc(z.subtotal,discount,rawTax,isInter),supplierSnapshot={companyName:cfg.companyName||'ANANTA INDUSTRIES',companyAddress:cfg.companyAddress||'',companyGSTIN:gst,companyState:cfg.companyState||'',companyStateCode:cfg.companyStateCode||'',companyPincode:cfg.companyPincode||'',companyPhone:cfg.companyPhone||'',companyEmail:cfg.companyEmail||'',authorizedSignatory:cfg.authorizedSignatory||'',bankName:cfg.bankName||'',accountNo:cfg.accountNo||'',ifsc:cfg.ifsc||'',upiId:cfg.upiId||'',defaultTerms:cfg.defaultTerms||''},placeOfSupply=c.state||'',placeOfSupplyCode=c.stateCode||(String(c.gst||'').match(/^\d{2}/)?.[0]||'');const inv={id:id('inv'),number:nextNo(s,'invoice'),date:now(),clientId:c.id,clientName:c.name,clientSnapshot:{...c},supplierSnapshot,placeOfSupply,placeOfSupplyCode,deliveryAddress:c.deliveryAddress||c.address||'',reverseCharge:payload.reverseCharge==='Yes'?'Yes':'No',items:z.rows,subtotal:z.subtotal,discount,...tx,total:tx.taxable+tx.tax,cost:z.cost,profit:tx.taxable-z.cost,notes:payload.notes||'',paymentStatus:'Unpaid',paidAmount:0,balance:tx.taxable+tx.tax,status:'Active',createdBy:req.user.name,createdByRole:req.user.role,sourceQuotationId:sourceQuotation?.id||null};s.invoices.push(inv);audit(s,req,'INVOICE_CREATE',inv.number);for(const r of z.rows){const p=s.products.find(x=>x.id===r.productId);recordStock(s,p,-r.qty,'OUT',inv.number,req.user.name,'Sales invoice')}if(sourceQuotation){sourceQuotation.status='Converted';sourceQuotation.invoiceId=inv.id}return inv}
app.get('/api/invoices',auth,(req,res)=>{const s=ensure(read());res.json(s.invoices.slice().reverse().map(v=>{const x=JSON.parse(JSON.stringify(v));x.supplierSnapshot=x.supplierSnapshot||{...s.settings};if(req.user.role==='biller'){delete x.clientSnapshot;delete x.cost;delete x.profit;x.items=(x.items||[]).map(({purchasePrice,...r})=>r)}return x}))});
app.post('/api/invoices',auth,(req,res)=>{try{const s=ensure(read()),inv=createInvoice(s,req,req.body);write(s);const out={...inv};if(req.user.role==='biller'){delete out.clientSnapshot;delete out.cost;delete out.profit}res.json(out)}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/quotations/:id/convert',auth,admin,(req,res)=>{try{const s=ensure(read()),q=s.quotations.find(x=>x.id===req.params.id);if(!q)throw Error('Quotation not found');if(q.status==='Converted')throw Error('Quotation already converted');const inv=createInvoice(s,req,{clientId:q.clientId,items:q.items.map(x=>({productId:x.productId,qty:x.qty,rate:x.rate})),discount:q.discount,notes:q.notes},q);write(s);const out={...inv};if(req.user.role==='biller'){delete out.clientSnapshot;delete out.cost;delete out.profit}res.json(out)}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/invoices/:id',auth,(req,res)=>{const s=ensure(read()),v=s.invoices.find(x=>x.id===req.params.id);if(!v)return res.status(404).json({error:'Not found'});const x=JSON.parse(JSON.stringify(v));x.supplierSnapshot=x.supplierSnapshot||{...s.settings};if(req.user.role==='biller'){delete x.cost;delete x.profit;x.items=(x.items||[]).map(({purchasePrice,...r})=>r)}res.json(x)});
app.post('/api/invoices/:id/payments',auth,admin,(req,res)=>{try{const s=ensure(read()),inv=s.invoices.find(x=>x.id===req.params.id);if(!inv||inv.status==='Cancelled')throw Error('Invoice not available');const amount=n(req.body.amount);if(amount<=0||amount>n(inv.balance)+.01)throw Error('Enter a valid payment amount');const p={id:id('pay'),date:now(),invoiceId:inv.id,invoiceNumber:inv.number,clientId:inv.clientId,clientName:inv.clientName,amount,mode:req.body.mode||'Cash',reference:req.body.reference||'',createdBy:req.user.name};s.payments.push(p);audit(s,req,'PAYMENT_CREATE',`${inv.number} ₹${amount}`);inv.paidAmount=n(inv.paidAmount)+amount;inv.balance=Math.max(0,n(inv.total)-inv.paidAmount);inv.paymentStatus=inv.balance<=.01?'Paid':'Partial';write(s);res.json({payment:p,invoice:inv})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/invoices/:id/cancel',auth,admin,(req,res)=>{try{const s=ensure(read()),inv=s.invoices.find(x=>x.id===req.params.id);if(!inv||inv.status==='Cancelled')throw Error('Invoice not available');if(n(inv.paidAmount)>0)throw Error('Paid/partial invoice cannot be cancelled. Create credit note instead.');inv.status='Cancelled';inv.cancelledAt=now();audit(s,req,'INVOICE_CANCEL',inv.number);inv.cancelReason=req.body.reason||'';for(const r of inv.items){const p=s.products.find(x=>x.id===r.productId);if(p)recordStock(s,p,r.qty,'IN',inv.number,req.user.name,'Invoice cancelled - stock restored')}write(s);res.json(inv)}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/credit-notes',auth,admin,(req,res)=>res.json(ensure(read()).creditNotes.slice().reverse()));
app.post('/api/invoices/:id/credit-note',auth,admin,(req,res)=>{try{const s=ensure(read()),inv=s.invoices.find(x=>x.id===req.params.id);if(!inv)throw Error('Invoice not found');const amount=n(req.body.amount);if(amount<=0||amount>n(inv.total))throw Error('Enter valid credit amount');const cn={id:id('cn'),number:`CN/${fy()}/${String(s.creditNotes.length+1).padStart(4,'0')}`,date:now(),invoiceId:inv.id,invoiceNumber:inv.number,clientId:inv.clientId,clientName:inv.clientName,amount,reason:req.body.reason||'',createdBy:req.user.name};s.creditNotes.push(cn);audit(s,req,'CREDIT_NOTE_CREATE',cn.number);inv.creditAmount=n(inv.creditAmount)+amount;inv.balance=Math.max(0,n(inv.total)-n(inv.paidAmount)-inv.creditAmount);inv.paymentStatus=inv.balance<=.01?'Paid':n(inv.paidAmount)>0?'Partial':'Unpaid';write(s);res.json(cn)}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/ledger/:clientId',auth,admin,(req,res)=>{const s=ensure(read()),c=s.clients.find(x=>x.id===req.params.clientId);if(!c)return res.status(404).json({error:'Not found'});const invoices=s.invoices.filter(x=>x.clientId===c.id&&x.status!=='Cancelled'),payments=s.payments.filter(x=>x.clientId===c.id),credits=s.creditNotes.filter(x=>x.clientId===c.id),billed=invoices.reduce((a,b)=>a+n(b.total),0),paid=payments.reduce((a,b)=>a+n(b.amount),0),credited=credits.reduce((a,b)=>a+n(b.amount),0);res.json({client:c,billed,paid,credited,pending:Math.max(0,billed-paid-credited),invoices,payments,credits})});
// ---- Admin operations: expenses, reports, users, settings, audit and backup ----
app.get('/api/expenses',auth,admin,(req,res)=>res.json(ensure(read()).expenses.slice().reverse()));
app.post('/api/expenses',auth,admin,(req,res)=>{try{const s=ensure(read()),amount=n(req.body.amount);if(amount<=0)throw Error('Enter a valid expense amount');const x={id:id('exp'),date:req.body.date||now(),category:clean(req.body.category,80)||'General',description:clean(req.body.description,250),amount,mode:clean(req.body.mode,40)||'Cash',reference:clean(req.body.reference,100),createdBy:req.user.name};s.expenses.push(x);audit(s,req,'EXPENSE_CREATE',`${x.category} ₹${amount}`);write(s);res.json(x)}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/expenses/:id',auth,admin,(req,res)=>{const s=ensure(read()),x=s.expenses.find(v=>v.id===req.params.id);if(!x)return res.status(404).json({error:'Not found'});s.expenses=s.expenses.filter(v=>v.id!==x.id);audit(s,req,'EXPENSE_DELETE',`${x.category} ₹${x.amount}`);write(s);res.json({ok:true})});
app.get('/api/payments',auth,admin,(req,res)=>res.json(ensure(read()).payments.slice().reverse()));
app.get('/api/reports/summary',auth,admin,(req,res)=>{const s=ensure(read()),valid=s.invoices.filter(i=>i.status!=='Cancelled'),sales=valid.reduce((a,b)=>a+n(b.total),0),tax=valid.reduce((a,b)=>a+n(b.tax),0),taxable=valid.reduce((a,b)=>a+n(b.taxable),0),paid=s.payments.reduce((a,b)=>a+n(b.amount),0),cost=valid.reduce((a,b)=>a+n(b.cost),0),grossProfit=valid.reduce((a,b)=>a+n(b.profit),0),expenses=s.expenses.reduce((a,b)=>a+n(b.amount),0),purchaseTotal=s.purchases.reduce((a,b)=>a+n(b.total),0);res.json({sales,taxable,tax,paid,outstanding:Math.max(0,sales-paid),cost,grossProfit,expenses,netProfit:grossProfit-expenses,purchaseTotal,invoiceCount:valid.length,clientCount:s.clients.length,lowStock:s.products.filter(p=>n(p.stock)<=n(p.lowStock)).map(p=>({id:p.id,sku:p.sku,name:p.name,stock:p.stock,lowStock:p.lowStock,unit:p.unit}))})});
app.get('/api/users',auth,admin,(req,res)=>res.json(ensure(read()).users.map(({passwordHash,...u})=>u)));
app.post('/api/users',auth,admin,(req,res)=>{try{const s=ensure(read()),username=clean(req.body.username,80),password=String(req.body.password||''),role=req.body.role==='admin'?'admin':'biller';if(!username||password.length<8)throw Error('Username required and password must be at least 8 characters');if(s.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))throw Error('Username already exists');const u={id:id('u'),name:clean(req.body.name,100)||username,username,role,active:true,passwordHash:hashPassword(password)};s.users.push(u);audit(s,req,'USER_CREATE',`${username} (${role})`);write(s);res.json({id:u.id,name:u.name,username:u.username,role:u.role,active:u.active})}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/users/:id',auth,admin,(req,res)=>{try{const s=ensure(read()),u=s.users.find(x=>x.id===req.params.id);if(!u)throw Error('User not found');if(u.id===req.user.id&&req.body.active===false)throw Error('You cannot disable your own account');if(req.body.name!==undefined)u.name=clean(req.body.name,100);if(req.body.role!==undefined)u.role=req.body.role==='admin'?'admin':'biller';if(req.body.active!==undefined)u.active=!!req.body.active;if(req.body.password){if(String(req.body.password).length<8)throw Error('Password must be at least 8 characters');u.passwordHash=hashPassword(req.body.password)}audit(s,req,'USER_UPDATE',u.username);write(s);res.json({id:u.id,name:u.name,username:u.username,role:u.role,active:u.active})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/audit',auth,admin,(req,res)=>res.json(ensure(read()).auditLogs.slice(0,500)));
app.get('/api/settings',auth,admin,(req,res)=>res.json(ensure(read()).settings));
app.put('/api/settings',auth,admin,(req,res)=>{try{const s=ensure(read()),gst=clean(req.body.companyGSTIN,20).toUpperCase();if(gst&&!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(gst))throw Error('Enter a valid 15-character company GSTIN');const stateCode=clean(req.body.companyStateCode,2);if(stateCode&&!/^\d{2}$/.test(stateCode))throw Error('State code must be 2 digits');s.settings={...s.settings,companyName:clean(req.body.companyName,120)||'ANANTA INDUSTRIES',companyAddress:clean(req.body.companyAddress,300),companyGSTIN:gst,companyState:clean(req.body.companyState,80)||'Gujarat',companyStateCode:stateCode||'24',companyPincode:clean(req.body.companyPincode,10),companyPhone:clean(req.body.companyPhone,30),companyEmail:clean(req.body.companyEmail,120),authorizedSignatory:clean(req.body.authorizedSignatory,120),bankName:clean(req.body.bankName,120),accountNo:clean(req.body.accountNo,40),ifsc:clean(req.body.ifsc,20).toUpperCase(),upiId:clean(req.body.upiId,120),defaultTerms:clean(req.body.defaultTerms,500),invoicePrefix:clean(req.body.invoicePrefix||s.settings.invoicePrefix,12).replace(/[^A-Za-z0-9_-]/g,''),quotationPrefix:clean(req.body.quotationPrefix||s.settings.quotationPrefix,12).replace(/[^A-Za-z0-9_-]/g,'')};audit(s,req,'SETTINGS_UPDATE','GST billing identity updated');write(s);res.json(s.settings)}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/backup',auth,admin,(req,res)=>{const s=ensure(read());audit(s,req,'BACKUP_EXPORT','Encrypted transport not required: local-only JSON export');write(s);res.setHeader('Content-Disposition',`attachment; filename="ananta-backup-${new Date().toISOString().slice(0,10)}.json"`);res.json(s)});

function startServer(port=PORT){
  const server=app.listen(port,'0.0.0.0');
  return server;
}
if(require.main===module){
  const server=startServer(PORT);
  server.on('listening',()=>console.log(`Ananta Management System listening on 0.0.0.0:${server.address().port}`));
}
module.exports={app,startServer,STORE};
